from user_manager import UserManager, UserAlreadyExistsError


def test_agregar_usuario_exitoso():
    # Arrange
    manager = UserManager()
    username = "kapu"
    password = "securepassword"

    # Act
    manager.add_user(username, password)

    # Assert
    assert manager.user_exists(username), \
        "El usuario debería existir después de ser agregado."
